name: Nightly release

on:
  workflow_dispatch:
    inputs:
      parameter:
        description: branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different runner if needed
    permissions: write-all

    env:
      TAG_NAME: nightly

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: development

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -d "$TAG_NAME" || true
          git push --delete origin "$TAG_NAME" || true
          
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build Shaded JAR
        run: mvn clean package

      - name: Create Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Nightly Release
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            /home/runner/work/Microbot/Microbot/runelite-client/target/microbot-*.jar