name: Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different runner if needed
    permissions: write-all

    env:
      TAG_NAME: 1.9.1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build Shaded JAR
        run: mvn clean package

      - name: Create Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            /home/runner/work/Microbot/Microbot/runelite-client/target/microbot-*.jar

      - name: Upload Jar
        uses: "bacongobbler/azure-blob-storage-upload@main"
        with:
          source_dir: runelite-client/target
          container_name: microbot
          connection_string: ${{ secrets.blobConnectionString }}
          extra_args: '--pattern *.jar --destination-path release'
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: 'true'